import 'dart:convert';

import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';
import 'package:oruma_app/features/reports/models/report_models.dart';
import 'package:oruma_app/features/reports/presentation/report_config.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class ReportPdfGenerator {
  const ReportPdfGenerator._();

  static Future<Uint8List> generate({
    required ReportDefinition definition,
    required ReportResult report,
    required ReportFilters filters,
    required String unitName,
    required String unitLocation,
    required String generatedBy,
    String? logoSource,
  }) async {
    final malayalamRegular = pw.Font.ttf(
      await rootBundle.load('assets/fonts/NotoSansMalayalam-Regular.ttf'),
    );
    final malayalamBold = pw.Font.ttf(
      await rootBundle.load('assets/fonts/NotoSansMalayalam-Bold.ttf'),
    );
    final regular = pw.Font.helvetica();
    final bold = pw.Font.helveticaBold();
    final logoBytes = await _loadLogo(logoSource);
    final logo = logoBytes == null ? null : pw.MemoryImage(logoBytes);
    final document = pw.Document(
      theme: pw.ThemeData.withFont(
        base: regular,
        bold: bold,
        fontFallback: [malayalamRegular, malayalamBold],
      ),
    );
    final dateFormat = DateFormat('dd MMM yyyy');
    final generatedFormat = DateFormat('dd MMM yyyy, hh:mm a');
    final period = filters.from == null && filters.to == null
        ? 'All time'
        : '${filters.from == null ? 'Beginning' : dateFormat.format(filters.from!)}'
              ' – ${filters.to == null ? 'Today' : dateFormat.format(filters.to!)}';
    final filterText = filters.extra.entries
        .where((entry) => entry.value.trim().isNotEmpty)
        .map((entry) => '${_label(entry.key)}: ${_label(entry.value)}')
        .join('  •  ');
    final columns = definition.columns;

    document.addPage(
      pw.MultiPage(
        pageFormat: columns.length > 8
            ? PdfPageFormat.a4.landscape
            : PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by $generatedBy',
              style: const pw.TextStyle(fontSize: 8),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 8),
            ),
          ],
        ),
        build: (context) => [
          pw.Container(
            padding: const pw.EdgeInsets.only(bottom: 12),
            decoration: const pw.BoxDecoration(
              border: pw.Border(
                bottom: pw.BorderSide(color: PdfColor.fromInt(0xFFCBD5E1)),
              ),
            ),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                if (logo != null)
                  pw.Container(
                    width: 46,
                    height: 46,
                    padding: const pw.EdgeInsets.all(2),
                    decoration: pw.BoxDecoration(
                      color: PdfColors.white,
                      border: pw.Border.all(color: PdfColor.fromHex('#E2E8F0')),
                      borderRadius: pw.BorderRadius.circular(9),
                    ),
                    child: pw.Image(logo, fit: pw.BoxFit.contain),
                  ),
                pw.SizedBox(width: 12),
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        unitName,
                        style: pw.TextStyle(font: bold, fontSize: 16),
                      ),
                      if (unitLocation.trim().isNotEmpty)
                        pw.Text(
                          unitLocation,
                          style: const pw.TextStyle(
                            fontSize: 9,
                            color: PdfColors.grey700,
                          ),
                        ),
                      pw.SizedBox(height: 5),
                      pw.Text(
                        '${definition.type.label} Report',
                        style: pw.TextStyle(
                          font: bold,
                          fontSize: 20,
                          color: PdfColor.fromHex('#0F766E'),
                        ),
                      ),
                    ],
                  ),
                ),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text(
                      period,
                      style: pw.TextStyle(font: bold, fontSize: 9),
                    ),
                    pw.Text(
                      generatedFormat.format(report.generatedAt.toLocal()),
                      style: const pw.TextStyle(
                        fontSize: 8,
                        color: PdfColors.grey700,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
          if (filters.search.trim().isNotEmpty || filterText.isNotEmpty) ...[
            pw.SizedBox(height: 10),
            pw.Text(
              [
                if (filters.search.trim().isNotEmpty)
                  'Search: ${filters.search.trim()}',
                if (filterText.isNotEmpty) filterText,
              ].join('  •  '),
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
            ),
          ],
          pw.SizedBox(height: 14),
          pw.Wrap(
            spacing: 8,
            runSpacing: 8,
            children: definition.summaryLabels.entries.map((entry) {
              final value = report.summary[entry.key] ?? 0;
              return pw.Container(
                width: 105,
                padding: const pw.EdgeInsets.all(8),
                decoration: pw.BoxDecoration(
                  color: PdfColor.fromHex('#F8FAFC'),
                  border: pw.Border.all(color: PdfColor.fromHex('#E2E8F0')),
                  borderRadius: pw.BorderRadius.circular(6),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      entry.value,
                      style: const pw.TextStyle(
                        fontSize: 8,
                        color: PdfColors.grey700,
                      ),
                    ),
                    pw.SizedBox(height: 3),
                    pw.Text(
                      formatReportValue(entry.key, value),
                      style: pw.TextStyle(font: bold, fontSize: 13),
                    ),
                  ],
                ),
              );
            }).toList(),
          ),
          pw.SizedBox(height: 16),
          if (report.rows.isEmpty)
            pw.Center(child: pw.Text('No records match the selected filters.'))
          else
            pw.TableHelper.fromTextArray(
              headers: columns.map((column) => column.label).toList(),
              data: report.rows.map((row) {
                return columns
                    .map(
                      (column) =>
                          formatReportValue(column.key, row[column.key]),
                    )
                    .toList();
              }).toList(),
              headerStyle: pw.TextStyle(
                font: bold,
                fontSize: columns.length > 8 ? 6.5 : 7.5,
                color: PdfColors.white,
              ),
              headerDecoration: pw.BoxDecoration(
                color: PdfColor.fromHex('#0F766E'),
              ),
              cellStyle: pw.TextStyle(fontSize: columns.length > 8 ? 6 : 7),
              cellPadding: const pw.EdgeInsets.symmetric(
                horizontal: 4,
                vertical: 5,
              ),
              oddRowDecoration: pw.BoxDecoration(
                color: PdfColor.fromHex('#F8FAFC'),
              ),
              border: pw.TableBorder.all(
                color: PdfColor.fromHex('#E2E8F0'),
                width: 0.4,
              ),
            ),
        ],
      ),
    );

    return document.save();
  }

  static String fileName(ReportType type) {
    final stamp = DateFormat('yyyyMMdd_HHmm').format(DateTime.now());
    return '${type.apiSlug}_report_$stamp.pdf';
  }

  static Future<Uint8List?> _loadLogo(String? source) async {
    if (source != null && source.startsWith('data:image/')) {
      final commaIndex = source.indexOf(',');
      if (commaIndex >= 0) {
        try {
          return base64Decode(source.substring(commaIndex + 1));
        } catch (_) {
          return null;
        }
      }
    }

    if (source != null &&
        (source.startsWith('http://') || source.startsWith('https://'))) {
      try {
        final response = await http
            .get(Uri.parse(source))
            .timeout(const Duration(seconds: 8));
        if (response.statusCode >= 200 && response.statusCode < 300) {
          return response.bodyBytes;
        }
      } catch (_) {
        return null;
      }
    }
    return null;
  }

  static String _label(String value) {
    return value
        .replaceAllMapped(
          RegExp(r'([a-z])([A-Z])'),
          (match) => '${match[1]} ${match[2]}',
        )
        .replaceAll('_', ' ')
        .split(' ')
        .where((part) => part.isNotEmpty)
        .map((part) => '${part[0].toUpperCase()}${part.substring(1)}')
        .join(' ');
  }
}
