class EquipmentDamageRecord {
  final String? id;
  final String? damageReason;
  final DateTime damagedAt;
  final String? damagedBy;
  final DateTime? repairedAt;
  final String? repairedBy;

  const EquipmentDamageRecord({
    this.id,
    this.damageReason,
    required this.damagedAt,
    this.damagedBy,
    this.repairedAt,
    this.repairedBy,
  });

  factory EquipmentDamageRecord.fromJson(Map<String, dynamic> json) {
    return EquipmentDamageRecord(
      id: json['id']?.toString() ?? json['_id']?.toString(),
      damageReason: json['damageReason']?.toString(),
      damagedAt:
          DateTime.tryParse(json['damagedAt']?.toString() ?? '') ??
          DateTime.fromMillisecondsSinceEpoch(0),
      damagedBy: _actorLabel(json['damagedBy']),
      repairedAt: DateTime.tryParse(json['repairedAt']?.toString() ?? ''),
      repairedBy: _actorLabel(json['repairedBy']),
    );
  }

  bool get isRepaired => repairedAt != null;

  static String? _actorLabel(dynamic value) {
    if (value is Map) {
      return value['name']?.toString() ??
          value['id']?.toString() ??
          value['_id']?.toString();
    }
    return value?.toString();
  }
}

/// Equipment model that matches the backend schema.
/// Each equipment now has a unique ID for individual tracking.
class Equipment {
  final String? id;
  final String uniqueId; // Unique ID like "WH-001", "WH-002"
  final String serialNo; // Base serial number (e.g., "WH")
  final String name;
  final int quantity; // Always 1 for individual items
  final String purchasedFrom;
  final DateTime? purchaseDate;
  final String place;
  final String phone;
  final String? storagePlace; // Storage location (e.g., "Store")
  final String status; // 'available', 'supplied', 'maintenance'
  final String? damageReason;
  final DateTime? damagedAt;
  final String? damagedBy;
  final DateTime? repairedAt;
  final List<EquipmentDamageRecord> damageHistory;
  final String? createdBy;
  final DateTime? createdAt;

  const Equipment({
    this.id,
    required this.uniqueId,
    required this.serialNo,
    required this.name,
    required this.quantity,
    required this.purchasedFrom,
    this.purchaseDate,
    required this.place,
    required this.phone,
    this.storagePlace,
    this.status = 'available',
    this.damageReason,
    this.damagedAt,
    this.damagedBy,
    this.repairedAt,
    this.damageHistory = const [],
    this.createdBy,
    this.createdAt,
  });

  /// Create Equipment from JSON (API response).
  factory Equipment.fromJson(Map<String, dynamic> json) {
    return Equipment(
      id: json['id']?.toString() ?? json['_id']?.toString(),
      uniqueId: json['uniqueId']?.toString() ?? '',
      serialNo: json['serialNo']?.toString() ?? '',
      name: json['name']?.toString() ?? '',
      quantity: (json['quantity'] is int)
          ? json['quantity'] as int
          : int.tryParse(json['quantity']?.toString() ?? '1') ?? 1,
      purchasedFrom: json['purchasedFrom']?.toString() ?? '',
      purchaseDate: json['purchaseDate'] != null
          ? DateTime.tryParse(json['purchaseDate'].toString())
          : null,
      place: json['place']?.toString() ?? '',
      phone: json['phone']?.toString() ?? '',
      storagePlace: json['storagePlace']?.toString(),
      status: json['status']?.toString() ?? 'available',
      damageReason: json['damageReason']?.toString(),
      damagedAt: json['damagedAt'] != null
          ? DateTime.tryParse(json['damagedAt'].toString())
          : null,
      damagedBy: json['damagedBy']?.toString(),
      repairedAt: json['repairedAt'] != null
          ? DateTime.tryParse(json['repairedAt'].toString())
          : null,
      damageHistory: (json['damageHistory'] as List<dynamic>? ?? const [])
          .whereType<Map>()
          .map(
            (record) => EquipmentDamageRecord.fromJson(
              Map<String, dynamic>.from(record),
            ),
          )
          .toList(growable: false),
      createdBy: json['createdBy'] is Map
          ? json['createdBy']['name']?.toString()
          : json['createdBy']?.toString(),
      createdAt: json['createdAt'] != null
          ? DateTime.tryParse(json['createdAt'].toString())
          : null,
    );
  }

  /// Convert Equipment to JSON for API requests.
  /// Note: Does not include uniqueId as it's auto-generated by the server.
  Map<String, dynamic> toJson() {
    return {
      'serialNo': serialNo,
      'name': name,
      'quantity': quantity,
      'purchasedFrom': purchasedFrom,
      if (purchaseDate != null) 'purchaseDate': purchaseDate!.toIso8601String(),
      'place': place,
      'phone': phone,
      if (storagePlace != null) 'storagePlace': storagePlace,
    };
  }

  /// Create a copy with updated fields.
  Equipment copyWith({
    String? id,
    String? uniqueId,
    String? serialNo,
    String? name,
    int? quantity,
    String? purchasedFrom,
    DateTime? purchaseDate,
    String? place,
    String? phone,
    String? storagePlace,
    String? status,
    String? damageReason,
    DateTime? damagedAt,
    String? damagedBy,
    DateTime? repairedAt,
    List<EquipmentDamageRecord>? damageHistory,
  }) {
    return Equipment(
      id: id ?? this.id,
      uniqueId: uniqueId ?? this.uniqueId,
      serialNo: serialNo ?? this.serialNo,
      name: name ?? this.name,
      quantity: quantity ?? this.quantity,
      purchasedFrom: purchasedFrom ?? this.purchasedFrom,
      purchaseDate: purchaseDate ?? this.purchaseDate,
      place: place ?? this.place,
      phone: phone ?? this.phone,
      storagePlace: storagePlace ?? this.storagePlace,
      status: status ?? this.status,
      damageReason: damageReason ?? this.damageReason,
      damagedAt: damagedAt ?? this.damagedAt,
      damagedBy: damagedBy ?? this.damagedBy,
      repairedAt: repairedAt ?? this.repairedAt,
      damageHistory: damageHistory ?? this.damageHistory,
      createdBy: createdBy,
      createdAt: createdAt,
    );
  }

  /// Check if equipment is available for supply
  bool get isAvailable => status == 'available';

  bool get isDamaged => status == 'maintenance';

  /// Get status color for UI
  String get statusLabel {
    switch (status) {
      case 'available':
        return 'Available';
      case 'supplied':
        return 'Supplied';
      case 'maintenance':
        return 'Damaged';
      default:
        return status;
    }
  }

  @override
  String toString() {
    return 'Equipment(uniqueId: $uniqueId, name: $name, status: $status)';
  }
}
